# variaveis
# inteiros, real, cadeia logico
rpm = 2000 # variavel rmp guarda (inteiro)
preço_passagem = 6.7 #variavel preço_passagem guarda (real
produto = "Mochila Adidas" #variavel produto guarda "mochila Adidas" (cade1)
ehMaiorIdade = True #variavel ehMaiorIdade guarda True (logico)


valor_produto = 29.90
quantidade_itens = 3
nome_usuario = "felca"
ehAluno = True

print("Valor do produto:", valor_produto)
print("Quantidade de itens:", quantidade_itens)
print("Nome do usuário:", nome_usuario)
print("O usuário é aluno?", ehAluno)
 
numero1 = input("digite o primeiro numero")
numero2 = input("digite o segundo numero")

nome_usuario1 = input ("digite o nome_usuario")
resultado = numero1 + numero2 
print(resultado)

print,input(1 + 1 )

























# + - nome

# -- subtração

# * - multiplicação

# ** - elevado 


# escreva()

# leia()

# operadores aritiméticos 

# operadores realcionais 

# operadores logicos 